/// <reference types="vitest/config" />
import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import { fileURLToPath, URL } from 'node:url';

// The app (`index.html` -> `src/main.tsx`) and the marketing/guide/wiki site
// (`site/guide/**`, plain HTML+TS, no React) ship from ONE `vite build` as a
// multi-page app, so both land in a single GitHub Pages deploy. The app
// keeps the Pages root (`/afterlife/`) exactly as before — nothing about its
// own entry or bundle changes. `site/guide/**`'s HTML files are generated by
// `site/scripts/build-pages.mjs` (run as part of `npm run build`, before
// `vite build`) from templates in `site/scripts/`; see that script before
// editing wiki/landing copy by hand.
//
// Vite mirrors an HTML entry's path-relative-to-root in its build output, so
// `site/guide/index.html` lands at `dist/site/guide/index.html` — but the
// deployed URL is `/afterlife/guide/`, not `/afterlife/site/guide/`.
// `site/scripts/postbuild-flatten.mjs` (wired as npm's `postbuild` lifecycle
// script, so it runs after `npm run build` without swallowing a forwarded
// `--base` flag) moves the output up a level after the production build.
// This dev-only plugin gives the SAME URLs during `vite dev` that the
// deployed build serves under its `/afterlife/` base — both the `/guide/...`
// rewrite to the real `/site/guide/...` path on disk, AND stripping the
// `/afterlife` base prefix itself (which only exists in dev as a *string* in
// every guide/wiki page's absolute hrefs — `vite dev` never applies a
// `base`, so nothing serves that prefix without this) — so a Playwright spec
// (or a person) can follow the exact hrefs rendered on the page in both
// environments.
function guideDevAliasPlugin(): Plugin {
  return {
    name: 'afterlife-guide-dev-alias',
    apply: 'serve',
    configureServer(server) {
      server.middlewares.use((req, _res, next) => {
        let url = req.url;
        if (url === '/afterlife' || url === '/afterlife/') url = '/';
        else if (url?.startsWith('/afterlife/')) url = url.slice('/afterlife'.length);
        if (url === '/guide' || url?.startsWith('/guide/')) url = `/site${url}`;
        req.url = url;
        next();
      });
    },
  };
}

const page = (p: string) => fileURLToPath(new URL(p, import.meta.url));

export default defineConfig({
  plugins: [react(), tailwindcss(), guideDevAliasPlugin()],
  resolve: {
    alias: { '@': fileURLToPath(new URL('./src', import.meta.url)) },
  },
  server: { port: 5173 },
  build: {
    target: 'es2022',
    sourcemap: true,
    rollupOptions: {
      input: {
        app: page('index.html'),
        guide: page('site/guide/index.html'),
        wiki: page('site/guide/wiki/index.html'),
        wikiGettingStarted: page('site/guide/wiki/getting-started/index.html'),
        wikiFundamentals: page('site/guide/wiki/fundamentals/index.html'),
        wikiSpecimens: page('site/guide/wiki/specimens/index.html'),
        wikiFeatures: page('site/guide/wiki/features/index.html'),
        wikiShortcuts: page('site/guide/wiki/shortcuts/index.html'),
        wikiHowItWorks: page('site/guide/wiki/how-it-works/index.html'),
        wikiVerification: page('site/guide/wiki/verification/index.html'),
      },
    },
  },
  test: {
    environment: 'jsdom',
    include: ['tests/**/*.test.ts', 'tests/**/*.test.tsx'],
    css: false,
  },
});
